name: Render Testpaper PDF on Push

on:
  push:
    paths:
      - 'Testpaper.qmd' #Trigger only when the paper changed
      - 'Introduction.qmd'

jobs:
  render_quarto:
    runs-on: ubuntu-latest

    container:
      image: alexrieber/rocker-quarto-r:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Mark repository as safe
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          
      - name: Install tinytex
        run: |
          R -e 'install.packages("tinytex", repos = "https://cran.rstudio.com")'
          R -e 'tinytex::install_tinytex()'

      - name: Install quarto-arxiv extension
        run: |
          # Send responses one by one using sequential echo commands
          { echo ""; sleep 1; echo "yes"; sleep 1; echo "yes"; sleep 1; echo "no"; } | quarto install extension mikemahoney218/quarto-arxiv
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        # By default, this compares the latest commit to the previous local commit.

      - name: Render changed QMDs
        shell: bash  # <--- Tells GitHub to use Bash
        run: |
          ALL_CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Changed files: $ALL_CHANGED_FILES"

          for file in $ALL_CHANGED_FILES; do
            if [[ "$file" == "Testpaper.qmd" || "$file" == "Introduction.qmd" ]]; then
              echo "Rendering $file..."
              quarto render "$file" --to pdf
            else
              echo "Skipping $file"
            fi
          done

      - name: Upload rendered PDFs
        uses: actions/upload-artifact@v3
        with:
          name: rendered_pdfs
          path: paper_replication/*.pdf
          if-no-files-found: ignore
