name: Render Testpaper PDF on Push

on:
  push:
    paths:
      - 'Testpaper.qmd' #Trigger only when the paper changed

jobs:
  render_quarto:
    runs-on: ubuntu-latest

    container:
      image: alexrieber/rocker-quarto-r:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install tinytex
        run: |
          R -e 'install.packages("tinytex", repos = "https://cran.rstudio.com")'
          R -e 'tinytex::install_tinytex()'

      - name: Install quarto-arxiv extension
        run: |
          # Send responses one by one using sequential echo commands
          { echo ""; sleep 1; echo "yes"; sleep 1; echo "yes"; sleep 1; echo "no"; } | quarto install extension mikemahoney218/quarto-arxiv
          
      - name: Render Testpaper.qmd
        run: |
          quarto render Testpaper.qmd --to pdf
